aspnet-core/src/HC.WeChat.Web.Host/Controllers/YiBinWXController.cs
using System;
using System.Linq;
using Abp.Authorization;
using HC.WeChat.Activities;
using HC.WeChat.ActivityGoodses;
using HC.WeChat.Authorization.WeChatOAuth;
using HC.WeChat.Configuration;
using HC.WeChat.Controllers;
using HC.WeChat.Models.WeChat;
using HC.WeChat.WechatAppConfigs;
using HC.WeChat.WechatEnums;
using HC.WeChat.WeChatUsers;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using Abp.Domain.Repositories;
using Abp.AutoMapper;
using HC.WeChat.WeChatUsers.Dtos;
using HC.WeChat.ActivityForms;
using HC.WeChat.ActivityBanquets;
using HC.WeChat.ActivityDeliveryInfos;
using Senparc.Weixin.MP.Helpers;
using Microsoft.AspNetCore.Http;
using HC.WeChat.ActivityFormLogs;
using Abp.Application.Services.Dto;

namespace HC.WeChat.Web.Host.Controllers
{
    [AbpAllowAnonymous]
    public class YiBinWXController : WeChatWebControllerBase
    {
        IWeChatOAuthAppService _weChatOAuthAppService;
        IWeChatUserAppService _weChatUserAppService;
        private readonly IConfigurationRoot _appConfiguration;
        private WeChatTenantSetting _settings;
        IActivityAppService _activityAppService;
        IActivityGoodsAppService _activityGoodsAppService;
        private readonly IRepository<WeChatUser, Guid> _wechatuserRepository;
        IActivityFormAppService _activityFormAppService;
        IActivityBanquetAppService _activityBanquetAppService;
        private int? tenantId;
        IActivityDeliveryInfoAppService _activityDeliveryInfoAppService;
        IActivityFormLogAppService _activityFormLogAppService;

        private string UserOpenId
        {
            get
            {
                if (HttpContext.Session.GetString("UserOpenId") == null)
                {
                    return string.Empty;
                }
                return HttpContext.Session.GetString("UserOpenId");
            }
            set
            {
                value = value ?? string.Empty;
                HttpContext.Session.SetString("UserOpenId", value);
            }
        }

        public YiBinWXController(IWechatAppConfigAppService wechatAppConfigAppService,
           IOptions<WeChatTenantSetting> settings,
           IWeChatOAuthAppService weChatOAuthAppService,
           IWeChatUserAppService weChatUserAppService,
           IActivityAppService activityAppService,
           IActivityGoodsAppService activityGoodsAppService,
           IRepository<WeChatUser, Guid> wechatuserRepository,
           IActivityFormAppService activityFormAppService,
           IActivityBanquetAppService activityBanquetAppService,
           IActivityDeliveryInfoAppService activityDeliveryInfoAppService,
           IActivityFormLogAppService activityFormLogAppService,
        IHostingEnvironment env) : base(wechatAppConfigAppService)
        {
            _settings = settings.Value;
            tenantId = _settings.YiBin;
            InitAppConfigSetting();

            _weChatOAuthAppService = weChatOAuthAppService;
            _weChatUserAppService = weChatUserAppService;
            _activityAppService = activityAppService;
            _activityGoodsAppService = activityGoodsAppService;
            _weChatOAuthAppService.WechatAppConfig = WechatAppConfig;//注入配置
            _appConfiguration = env.GetAppConfiguration();
            _wechatuserRepository = wechatuserRepository;
            _activityFormAppService = activityFormAppService;
            _activityBanquetAppService = activityBanquetAppService;
            _activityDeliveryInfoAppService = activityDeliveryInfoAppService;
            _activityFormLogAppService = activityFormLogAppService;
        }

        protected override int? GetTenantId()
        {
            return tenantId;
        }

        private void SetUserOpenId(string code)
        {
            if (string.IsNullOrEmpty(code))
            {
                return;
            }
            //如果userId为null 则需要通过code重新获取
            if (string.IsNullOrEmpty(UserOpenId))
            {
                try
                {
                    var oauth = _weChatOAuthAppService.GetAccessTokenAsync(code).Result;
                    UserOpenId = oauth.openid;
                }
                catch (Exception ex)
                {
                    Logger.ErrorFormat("GetAccessTokenAsync Exception:{0}", ex.Message);
                }
                //UserOpenId = code;
            }
        }

        /// <summary>
        /// 用户绑定
        /// </summary>
        public IActionResult BindUser(string code, string state)
        {
            //Logger.InfoFormat("code:{0} state:{1}", code, state);
            //var oauth = _weChatOAuthAppService.GetAccessTokenAsync(code).Result;
            //UserOpenId = "o5Cto1SDboPrAwY9UyCTktFVpKBc";//客户经理
            //UserOpenId = "o5Cto1d1Vv-s-ytAZyCkWBQRvsBo";//零售客户

            //存储openId 避免重复提交
            SetUserOpenId(code);

            var tenantId = GetTenantId();
            //var openid = "C9E6F8A3-6A08-418A-A258-0ABCBEC17573";
            var user = _weChatUserAppService.GetWeChatUserAsync(UserOpenId, tenantId).Result;
            if (user == null)
            {
                user = new WeChatUserListDto();
            }
            //var wuser = _weChatOAuthAppService.GetUserInfoAsync(oauth.access_token, oauth.openid).Result;
            user.NickName = user.NickName;
            //user.HeadImgUrl = wuser.headimgurl;
            if (user.UserType == UserTypeEnum.零售客户 || user.UserType == UserTypeEnum.公司员工)
            {
                var formCount = _activityFormAppService.GetActivityFormCountByUserAsync(user).Result;
                //ViewBag.OutstandingCount = formCount.OutstandingCount;
                //ViewBag.CompletedCount = formCount.CompletedCount;
                ViewBag.FormCount = formCount.TotalCount;
                ViewBag.UserLevel = formCount.UserLevel;
                ViewBag.PendingCount = formCount.PendingCount;
                user.HeadImgUrl = user.HeadImgUrl ?? "static/img/index/timg-4.jpeg";
                return View("UserIndex", user);
            }

            ViewBag.NickName = user.NickName;
            ViewBag.OpenId = UserOpenId;
            ViewBag.TenantId = tenantId;
            var root = _appConfiguration["App:ServerRootAddress"];
            ViewBag.ServerRootAddress = root;
            //var url = root + "YiBinWX/BindUser";
            //ViewBag.Url = _weChatOAuthAppService.GetAuthorizeUrl(url, tenantId.ToString(), Senparc.Weixin.MP.OAuthScope.snsapi_base);
            //Logger.InfoFormat("Url:{0}", ViewBag.Url);
            return View();
        }

        /// <summary>
        /// 用户个人中心
        /// </summary>
        public IActionResult UserIndex()
        {
            var user = _wechatuserRepository.GetAll().Where(r => r.TenantId == AbpSession.TenantId).FirstOrDefault();
            return View(user.MapTo<WeChatUserListDto>());
        }

        /// <summary>
        /// 关于我们
        /// </summary>
        public IActionResult About()
        {
            return Redirect("/YiBinWX/company_info.html");
        }

        /// <summary>
        /// 客户热线
        /// </summary>
        public IActionResult CustomerServer()
        {
            return Redirect("/YiBinWX/service.html");
        }

        /// <summary>
        /// 附近店铺
        /// </summary>
        public IActionResult NearShop()
        {
            return View();
        }

        /// <summary>
        /// 专卖许可
        /// </summary>
        public IActionResult License()
        {
            return Redirect("/YiBinWX/process.html");
        }

        /// <summary>
        /// 意见反馈
        /// </summary>
        public IActionResult AdviseBack(string code, string stat)
        {
            //var oauth = _weChatOAuthAppService.GetAccessTokenAsync(code).Result;
            //var openid = "C9E6F8A3-6A08-418A-A258-0ABCBEC17573";
            //存储openId 避免重复提交
            SetUserOpenId(code);

            ViewBag.OpenId = UserOpenId;
            ViewBag.TenantId = tenantId;
            var root = _appConfiguration["App:ServerRootAddress"];
            ViewBag.ServerRootAddress = root;
            return View();
        }

        /// <summary>
        /// 问卷调查
        /// </summary>
        public IActionResult Question(string code, string state)
        {
            //var oauth = _weChatOAuthAppService.GetAccessTokenAsync(code).Result;
            //var openid = "C9E6F8A3-6A08-418A-A258-0ABCBEC17573";
            //存储openId 避免重复提交
            SetUserOpenId(code);

            ViewBag.OpenId = UserOpenId;
            ViewBag.TenantId = tenantId;
            var root = _appConfiguration["App:ServerRootAddress"];
            ViewBag.ServerRootAddress = root;
            return View();
        }

        /// <summary>
        /// 营销活动
        /// </summary>
        public IActionResult Activity()
        {
            var activity = _activityAppService.GetTenantWeChatActivityAsync(tenantId).Result;
            if (activity == null)
            {
                return View("NoActivity");
            }

            if (string.IsNullOrEmpty(UserOpenId))
            {
                var url = _appConfiguration["App:ServerRootAddress"] + "/YiBinWX/ActivityForm";
                ViewBag.FormUrl = _weChatOAuthAppService.GetAuthorizeUrl(url, activity.Id.ToString(), Senparc.Weixin.MP.OAuthScope.snsapi_base);
            }
            else
            {
                ViewBag.FormUrl = Url.Action("ActivityForm", new { state = activity.Id.ToString() });
            }
           
            //ViewBag.FormUrl = url + "?state=" + activity.Id;
            ViewBag.FlowUrl = Url.Action("ActivityFlow");
            return View();
        }

        /// <summary>
        /// 没有上线的活动
        /// </summary>
        public IActionResult NoActivity()
        {
            return View();
        }

        /// <summary>
        /// 活动流程

aspnet-core/src/HC.WeChat.Web.Host/Views/YiBinWX/ActivityFromApply.cshtml
@model HC.WeChat.ActivityForms.Dtos.ActivityFormForWechat
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" name="viewport" />
    <title>宜宾烟草</title>
    <link href="~/YiBinWX/static/css/commons.css" rel="stylesheet" />
    <link rel="stylesheet" href="//res.wx.qq.com/open/libs/weui/1.1.2/weui.min.css" />
</head>
<body class="bg_gary">
    <div class="weui-tab">
        <div class="weui-navbar">
            <div class="weui-navbar__item weui-bar__item_on" onclick="navbarClick(this, 1)">
                未邮寄
            </div>
            <div class="weui-navbar__item" onclick="navbarClick(this, 2)">
                已邮寄
            </div>
        </div>
        <div class="weui-tab__panel preview">
            <div class="page__bd" id="noSendPage">
                @foreach (var item in Model.ActivityFormNoSendList)
                {
                    <div class="weui-form-preview">
                        <div class="weui-form-preview__hd">
                            <div class="weui-form-preview__item">
                                <label class="weui-form-preview__label">@item.GoodsSpecification</label>
                                <em class="weui-form-preview__value">@(item.Num)条</em>
                            </div>
                        </div>
                        <div class="weui-form-preview__bd">
                            <p>
                                <label class="weui-form-preview__label">单号</label>
                                <span class="weui-form-preview__value">@item.FormCode</span>
                            </p>
                            <p>
                                <label class="weui-form-preview__label">@item.StatusName</label>
                                <span class="weui-form-preview__value">@item.CreationTime.ToString("yyyy-MM-dd HH:mm")</span>
                            </p>
                        </div>
                        <div class="weui-form-preview__ft">
                            <a class="weui-form-preview__btn weui-form-preview__btn_primary" href="@Url.Action("ActivityFromDetail","YiBinWX", new { id = item.Id, openId = Model.OpenId })">查看详细</a>
                        </div>
                    </div>
                    <br />
                }
                @if (Model.ActivityFormNoSendList.Count() == 0)
                {
                    <div class="weui-loadmore weui-loadmore_line">
                        <span class="weui-loadmore__tips">暂无数据</span>
                    </div>

                }
            </div>
            <div class="page__bd" id="sendOutPage" style="display:none">
                <div class="weui-cells__title">已邮寄显示最近50条数据</div>
                @foreach (var item in Model.ActivityFormSendOutList)
                {
                    <div class="weui-form-preview">
                        <div class="weui-form-preview__hd">
                            <div class="weui-form-preview__item">
                                <label class="weui-form-preview__label">@item.GoodsSpecification</label>
                                <em class="weui-form-preview__value">@(item.Num)条</em>
                            </div>
                        </div>
                        <div class="weui-form-preview__bd">
                            <p>
                                <label class="weui-form-preview__label">单号</label>
                                <span class="weui-form-preview__value">@item.FormCode</span>
                            </p>
                            <p>
                                <label class="weui-form-preview__label">@item.StatusName</label>
                                <span class="weui-form-preview__value">@item.CreationTime.ToString("yyyy-MM-dd HH:mm")</span>
                            </p>
                        </div>
                        <div class="weui-form-preview__ft">
                            <a class="weui-form-preview__btn weui-form-preview__btn_primary" href="@Url.Action("ActivityFromDetail","YiBinWX", new { id = item.Id, openId = Model.OpenId })">查看详细</a>
                        </div>
                    </div>
                    <br />
                }
                @if (Model.ActivityFormSendOutList.Count() == 0)
                {
                    <div class="weui-loadmore weui-loadmore_line">
                        <span class="weui-loadmore__tips">暂无数据</span>
                    </div>

                }
            </div>
        </div>
    </div>
    <br />
    <div class="weui-footer">
        <p class="weui-footer__text">酒都金叶 | 宜宾烟草</p>
    </div>
    <script type="text/javascript" src="static/js/jquery.min.js"></script>
    <script type="text/javascript">
        function navbarClick(obj, num) {
            $(".weui-navbar__item").removeClass("weui-bar__item_on");
            $(obj).addClass("weui-bar__item_on");
            if (num == 1) {
                $("#noSendPage").show();
                $("#sendOutPage").hide();
            } else {
                $("#noSendPage").hide();
                $("#sendOutPage").show();
            }
        }
    </script>
</body>
</html>

aspnet-core/src/HC.WeChat.Web.Host/Views/YiBinWX/ActivityFromApplyDetail.cshtml
 @model HC.WeChat.ActivityForms.Dtos.ActivityFormListDto
 
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" name="viewport" />
    <title>活动申请单详情</title>
    <link href="~/YiBinWX/static/css/base.css" rel="stylesheet" />
    <link href="~/YiBinWX/static/css/commons.css" rel="stylesheet" />
    <link href="~/YiBinWX/static/css/personal.css" rel="stylesheet" />
</head>
<body class="bg_gary">
    <div id="background" class="background" style="display: none; "></div>
    <div id="progressBar" class="progressBar" style="display: none; ">正在提交中，请稍等...</div>
    <div class="all_width">
        <div class="header bg_green tc">
            活动申请单详情
        </div>
        <ul class="personal_link all_width"> 
            <li>
                <label class="fl main_green">
                    申请单号
                </label>
                <label class="fl  ml20" style="font-weight:bold;">@Model.FormCode</label>
            </li>
            <li>
                <label class="fl main_green">
                    活动名称
                </label>
                <label class="fl  ml20">@Model.ActivityName</label>
            </li>
            <li>
                <label class="fl main_green">
                    零售客户
                </label>
                <label class="fl  ml20">@Model.RetailerName</label>
            </li>
            <li>
                <label class="fl main_green">
                    客户经理
                </label>
                <label class="fl  ml20">@Model.ManagerName</label>
            </li>
            <li>
                <label class="fl main_green">
                    商品规格
                </label>
                <label class="fl  ml20">@Model.GoodsSpecification</label>
            </li>
            <li>
                <label class="fl main_green">
                    申请数量
                </label>
                <label class="fl  ml20">@Model.Num</label>
            </li>
            <li>
                <label class="fl main_green">
                    申请人
                </label>
                <label class="fl  ml20">&nbsp;&nbsp;&nbsp;@Model.CreationUser</label>
            </li>
            <li>
                <label class="fl main_green">
                    申请时间
                </label>
                <label class="fl  ml20">@Model.CreationTime.ToString("yyyy-MM-dd")</label>
            </li>
            <li>
                <label class="fl main_green">
                    申请理由
                </label>
                <label class="fl  ml20">@Model.Reason</label>
            </li>
            <li>
                <label class="fl main_green">
                    审批状态
                </label>
                <label class="fl  ml20" style="font-weight:bold;">@Model.StatusName</label>
            </li>
            <li>
                <label class="fl main_green">
                    完成时间
                </label>
                <label class="fl  ml20">@ViewBag.CompleteTime</label>
            </li>
            <li style="display:none;height:90px;" id="message" class="advise_warp">
                <label class="fl main_green">
                    审批意见
                </label>
                @*<label class="fl  ml20"></label>*@
                <textarea id="checkMessage" style="width:66%;height:100%;" class="fl  ml20 contain_entry" placeholder="请输入审批意见"></textarea>
            </li>
        </ul>
        <input type="hidden" id="hidOpenId" value="@ViewBag.OpenId" />
        <input type="hidden" id="hidStatus" value="@ViewBag.Status" />
        <input type="hidden" id="hidUserType" value="@ViewBag.UserType" />
        <input type="hidden" id="hidIsBanquent" value="@ViewBag.IsBanquent" />

    </div>
    <div class="width_90 mt30 mb20" id="devButton">
        @*<input type="button" id="updateBtn" style="display:none" class="middel_btn fr ok" value="修改商品信息" onclick="javascript:window.location.href='@Url.Action("ActivityGoods", "YiBinWX", new { id = Model.Id })'" />*@
        <input type="button" id="cancelBtn"  class="middel_btn fl cancel" value="取消" onclick="Cancel()"/>
        <input type="button" id="firstCheckBtn" style="display:none" class="middel_btn fr ok" value="初审通过" onclick="StatusCheck(2)" />
        <input type="button" id="returnCheckBtn" style="display:none" class="middel_btn fr ok" value="资料完善" onclick="javascript:window.location.href='@Url.Action("ActivityBanquet", "YiBinWX", new { actFormId = Model.Id,actFormStatus=ViewBag.Status, openid = ViewBag.OpenId , userType = ViewBag.UserType })'" />
        <input type="button" id="marketingBtn" style="display:none" class="middel_btn fr ok" value="资料审核" onclick="javascript:window.location.href='@Url.Action("ActivityBanquet", "YiBinWX", new { actFormId = Model.Id,actFormStatus=ViewBag.Status, openid = ViewBag.OpenId, userType= ViewBag.UserType })'" />
        <input type="button" id="lookOverBtn" style="display:none" class="middel_btn fr ok" value="查看资料" onclick="javascript:window.location.href='@Url.Action("ActivityBanquet", "YiBinWX", new { actFormId = Model.Id,actFormStatus=ViewBag.Status, openid = ViewBag.OpenId, userType= ViewBag.UserType })'" />

    </div>
    <script type="text/javascript" src="~/YiBinWX/static/js/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            //申请单状态
            var status = $("#hidStatus").val();
            //用户类型
            var userType = $("#hidUserType").val();
            //宴席id
            var isBanquent = $("#hidIsBanquent").val();
            //推荐人信息id
            var deliveryId = '@ViewBag.DeliveryId';
            //if (status == 6) {
            //    $("#lookOverBtn").show();
            //} else {
                //登录用户为零售户时
                if (userType == 1) {
                    if (status == 1) {
                        //$("#cancelBtn").show();
                        $("#returnCheckBtn").hide();
                        $("#cancelBtn").removeClass("fl");
                        $("#devButton").css({ 'text-align': 'center' });
                    } else if (status == 2) {
                        //$("#cancelBtn").hide();
                        $("#returnCheckBtn").show();
                        //$("#returnCheckBtn").removeClass("fl");
                        //$("#devButton").css({ 'text-align': 'center' });
                    } else if (status == 5) {
                        //$("#cancelBtn").hide();
                        $("#returnCheckBtn").hide();
                        $("#cancelBtn").removeClass("fl");
                        $("#devButton").css({ 'text-align': 'center' });
                    } else { 
                        $("#cancelBtn").removeClass("fl");
                        $("#devButton").css({ 'text-align': 'center' });
                    }
                }
                //登录用户为客户经理时
                else if (userType == 2) {
                    //$("#cancelBtn").show();

                    //初审通过时
                    if (status == 2) {
                        if (isBanquent) {
                            $("#marketingBtn").show();
                            $("#returnCheckBtn").hide();
                            $("#firstCheckBtn").hide();
                            $("#message").hide();
                        } else {
                            $("#marketingBtn").hide();
                            $("#returnCheckBtn").show();
                            $("#firstCheckBtn").hide();
                            $("#message").hide();
                        }
                    }//提交申请时，还未进行初审时
                    else if (status == 1) {
                        $("#firstCheckBtn").show();
                        $("#message").show();
                        $("#marketingBtn").hide();
                        $("#returnCheckBtn").hide();
                    } else if (status == 5) {
                        $("#firstCheckBtn").hide();
                        $("#message").hide();
                        $("#marketingBtn").hide();
                        $("#returnCheckBtn").hide();
                        //但只有一个按钮时显示在中间位置
                        $("#cancelBtn").removeClass("fl");
                        $("#devButton").css({ 'text-align': 'center' });
                    } else if (status == 3) {
                        $("#firstCheckBtn").hide();
                        $("#message").hide();
                        $("#marketingBtn").hide();
                        $("#returnCheckBtn").hide();
                        $("#cancelBtn").removeClass("fl");
                        $("#devButton").css({ 'text-align': 'center' });
                    } else if (status == 6) {
                        $("#firstCheckBtn").hide();
                        $("#message").hide();
                        $("#marketingBtn").hide();
                        $("#returnCheckBtn").hide();
                        $("#cancelBtn").removeClass("fl");
                        $("#devButton").css({ 'text-align': 'center' });
                    } else if (status == 4) { 
                        $("#firstCheckBtn").hide();
                        $("#message").hide();
                        $("#marketingBtn").hide();
                        $("#returnCheckBtn").hide();
                        $("#cancelBtn").removeClass("fl");
                        $("#devButton").css({ 'text-align': 'center' });
                    }
                }
            //} WeixinJSBridge.call('closeWindow');
        });
        //取消、初审通过按钮
        function StatusCheck(status) {
            var content = status==2?"是否初审通过？":"是否取消申请？"
            if (confirm(content)) {
                var para = {};
                if (status == 2) {
                    para.Opinion = $("#checkMessage").val();
                }
                para.Status = status;
                para.Id = '@Model.Id';
                para.OpenId = $("#hidOpenId").val();
                para.TenantId = "@ViewBag.TenantId";
                var reqUrl = "@ViewBag.ServerRootAddress" + "/api/services/app/ActivityForm/ChangeActivityFormStatusWeChatAsync";
                var ajaxbg = $("#background, #progressBar");
                ajaxbg.show();
                $.ajax({
                    url: reqUrl,
                    type: "POST",
                    dataType: "JSON",
                    contentType: "application/json;charset=utf-8",
                    data: JSON.stringify(para),
                    success: function (data) {
                        ajaxbg.hide();
                        if (data.success) {
                            if (data.result.code == 0) {
                                alert(data.result.msg);
                                location.reload();
                                parent.location.reload();
                            } else {
                                alert(data.result.msg);
                            }
                        } else {
                            alert("保存异常！");
                        }
                    },
                    error: function () {
                        ajaxbg.hide();
                        alert("提交失败，稍后请重试！");
                    }
                });
            }
        }

        function Cancel() { 
            WeixinJSBridge.call('closeWindow');
            //window.close();
        }
    </script>
</body>
</html>

aspnet-core/src/HC.WeChat.Web.Host/Views/YiBinWX/ActivityFromPendingApply.cshtml
@model HC.WeChat.Models.WeChat.ActivityFromModel
@{
    ViewData["Title"] = "待审核表单";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" name="viewport" />
    <title>待审核</title>
    <link href="~/YiBinWX/static/css/commons.css" rel="stylesheet" />
    <link rel="stylesheet" href="//res.wx.qq.com/open/libs/weui/1.1.2/weui.min.css" />
</head>
<body class="bg_gary">
    <div id="loadingToast" style="display:none;">
        <div class="weui-mask_transparent"></div>
        <div class="weui-toast">
            <i class="weui-loading weui-icon_toast"></i>
            <p class="weui-toast__content">数据提交中</p>
        </div>
    </div>
    <div class="page__bd">
        <div class="weui-cells__title">待审核活动列表</div>
        @foreach (var item in Model.ActivityFormList)
        {
            <div class="weui-form-preview">
                <div class="weui-form-preview__hd">
                    <div class="weui-form-preview__item">
                        <label class="weui-form-preview__label">@item.GoodsSpecification</label>
                        <em class="weui-form-preview__value">@(item.Num)条</em>
                    </div>
                </div>
                <div class="weui-form-preview__bd">
                    <p>
                        <label class="weui-form-preview__label">单号</label>
                        <span class="weui-form-preview__value">@item.FormCode</span>
                    </p>
                    <p>
                        <label class="weui-form-preview__label">零售客户</label>
                        <span class="weui-form-preview__value">@item.RetailerName</span>
                    </p>
                    <p>
                        <label class="weui-form-preview__label">@item.StatusName</label>
                        <span class="weui-form-preview__value">@item.CreationTime.ToString("yyyy-MM-dd HH:mm")</span>
                    </p>
                </div>
                <div class="weui-form-preview__ft">
                    <a class="weui-form-preview__btn weui-form-preview__btn_primary" href="@Url.Action("ActivityFromDetail","YiBinWX", new { id = item.Id, openId = Model.OpenId, isApproval = true })">查看详细</a>
                    <a class="weui-form-preview__btn weui-form-preview__btn_primary" href="javascript:" onclick="StatusCheck('@item.Id')">审核通过</a>
                </div>
            </div>
            <br />
        }
        @if (Model.ActivityFormList.Count() == 0)
        {
            <div class="weui-loadmore weui-loadmore_line">
                <span class="weui-loadmore__tips">暂无数据</span>
            </div>

        }
    </div>
    <br />
    <div class="weui-footer">
        <p class="weui-footer__text">酒都金叶 | 宜宾烟草</p>
    </div>
    <script type="text/javascript" src="~/YiBinWX/static/js/jquery.min.js"></script>
    <script type="text/javascript">
        //审核通过
        function StatusCheck(id) {
            if (confirm('确定要审核通过吗？')) {
                var para = {};
                para.Opinion = '资料回传审核通过';
                para.Status = 4;
                para.Id = id;
                para.OpenId = '@Model.OpenId';
                para.TenantId = '@Model.TenantId';
                var reqUrl = "@ViewBag.ServerRootAddress" + "/api/services/app/ActivityForm/ChangeActivityFormStatusWeChatAsync";
                $("#loadingToast").show();
                $.ajax({
                    url: reqUrl,
                    type: "POST",
                    dataType: "JSON",
                    contentType: "application/json;charset=utf-8",
                    data: JSON.stringify(para),
                    success: function (data) {
                        $("#loadingToast").hide();
                        if (data.success) {
                            if (data.result.code == 0) {
                                alert(data.result.msg);
                                location.reload();
                                parent.location.reload();
                            } else {
                                alert(data.result.msg);
                            }
                        } else {
                            alert("保存异常！");
                        }
                    },
                    error: function () {
                        $("#loadingToast").hide();
                        alert("提交失败，稍后请重试！");
                    }
                });
            }
        }
    </script>
</body>
</html>